version: '3'

services:
  postgre:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssw0rd

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: p@ssw0rd

  nginx:
    image: nginx:latest
    depends_on:
      - web_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  web_server:
    build: .
    command: gunicorn app:app --host 0.0.0.0 --port 8000 --timeout 30 --workers 1
    depends_on:
      - postgre
      - mongodb

    expose:
      - 8000


# docker-compose up --build --scale web_server=5
